#!/bin/bash

# 在宝塔面板中创建网站的脚本

echo "🌐 配置宝塔面板网站..."

# 网站配置
DOMAIN="api.webspark.club"
PROJECT_DIR="/www/wwwroot/webspark-backend"

echo "通过宝塔面板 Web 界面完成以下配置："
echo ""
echo "1. 📱 登录宝塔面板 (默认端口 8888)"
echo "   http://你的服务器IP:8888"
echo ""
echo "2. 🌐 添加网站："
echo "   - 域名：$DOMAIN"
echo "   - 目录：$PROJECT_DIR"
echo "   - PHP版本：纯静态"
echo ""
echo "3. 🔒 配置 SSL 证书："
echo "   - 进入网站设置 → SSL"
echo "   - 选择 Let's Encrypt 免费证书"
echo "   - 或上传你的证书文件"
echo ""
echo "4. 🔧 配置反向代理："
echo "   - 进入网站设置 → 反向代理"
echo "   - 目标URL: http://127.0.0.1:3001"
echo "   - 发送域名: \$host"
echo "   - 添加以下请求头："
echo "     X-Real-IP: \$remote_addr"
echo "     X-Forwarded-For: \$proxy_add_x_forwarded_for"
echo "     X-Forwarded-Proto: \$scheme"
echo ""
echo "5. 🗄️  配置数据库："
echo "   - 进入数据库管理"
echo "   - 添加数据库：webspark"
echo "   - 记录数据库用户名和密码"
echo ""
echo "6. 📝 Node.js 项目管理："
echo "   - 进入软件商店 → Node项目管理"
echo "   - 添加 Node.js 项目"
echo "   - 项目路径：$PROJECT_DIR"
echo "   - 启动文件：dist/index.js"
echo "   - 端口：3001" 